### ISSUE TITLE
Channels with Invalid ASMR entries now fail to load

### ISSUE THREAD

**Issue by whgDosumi** [whgDosumi/ASMRchive#69]
![image](https://github.com/whgDosumi/ASMRchive/assets/60369937/b3df7fe2-961b-4170-8998-3b2352a993d6)

**Comment by whgDosumi** [comment]
This only happens on channels with an invalid ASMR entry, found the following error

> [17-Aug-2023 04:12:09 UTC] PHP Warning:  fopen(7ZvKUm8vj94/upload_date.txt): Failed to open stream: No such file or directory in /var/www/html/library.php on line 189
[17-Aug-2023 04:12:09 UTC] PHP Warning:  filesize(): stat failed for 7ZvKUm8vj94/upload_date.txt in /var/www/html/library.php on line 190
[17-Aug-2023 04:12:09 UTC] PHP Fatal error:  Uncaught TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/library.php:190
Stack trace:
#0 /var/www/html/library.php(190): fread()
#1 /var/ASMRchive/Houshou-Marine/channel.php(57): Video->__construct()
#2 {main}
  thrown in /var/www/html/library.php on line 190

This suggests that a boolean is being passed to fread on line 190 of library.php
I checked and 7ZvKUm8vj94/upload_date.txt doesn't exist as it's an invalid ASMR.

In the past, this didn't have any issues, but I suspect sloppy code is not checking for the file to exist before attempting to open the file, and probably returns 0 or false or something.
